--import Ideal.BasicDefinitions
--import Ideal.BasicLemmas
--import Ideal.IdealTrace
--import Ideal.IdealDeletion

--export Ideal.BasicDefinitions (*)
--export Ideal.BasicLemmas (*)
--export Ideal.IdealTrace (trace)
--export Ideal.IdealDeletion (deletion)
--export Ideal.IdealDeletion (idealdeletion)
--export Ideal.IdealDeletion (contraction)
--lake build
