--import Mathematics.BasicDefinitions
--import Mathematics.BasicLemmas
--import Mathematics.IdealTrace
--import Mathematics.IdealDeletion

--export Mathematics.BasicDefinitions (*)
--export Mathematics.BasicLemmas (*)
--export Mathematics.IdealTrace (trace)
--export Mathematics.IdealDeletion (deletion)
--export Mathematics.IdealDeletion (idealdeletion)
--export Mathematics.IdealDeletion (contraction)
--lake build
